### ISSUE TITLE
Cutting a new release with the ability to create GraphQLWebClientImpl instances

### ISSUE THREAD

**Issue by sdoxsee** [graphql-java-kickstart/graphql-spring-webclient#6]
**Is your feature request related to a problem? Please describe.**
I don't want to use the autoconfiguration or starter but only the library for now (as I'll provide my own WebClient bean that is configured to do OAuth2 token relay from the SecurityContext's JWT). However, I can't create my own a GraphQLWebClient instance due to https://github.com/graphql-java-kickstart/graphql-spring-webclient/issues/2#issuecomment-633193269. 

**Describe the solution you'd like**
Release 0.2.0 or something with that includes the following commit: https://github.com/graphql-java-kickstart/graphql-spring-webclient/commit/9987fee63223dcab55b6dc64c711f9de7a57fc54

**Describe alternatives you've considered**
I could create my own copied implementation of the library's Impl but that defeats the purpose of using this library

**Additional context**
N/A

**Comment by vojtapol** [comment]
Yes, we are planning to make a release soon.

**Comment by sdoxsee** [comment]
Great. Thanks!

**Comment by sdoxsee** [comment]
Any update on this? Thanks

**Comment by KurtStauffer** [comment]
I'm also needing this. Thanks

**Comment by vojtapol** [comment]
Will try to look into this as soon as possible.

**Comment by oliemansm** [comment]
You could have used the Snapshot release in the meantime, but noticed that wasn't documented in the README, so added a section there. Releasing version 0.2.0 today.

**Comment by oliemansm** [comment]
Version 0.2.0 is syncing to Maven Central now

**Comment by sdoxsee** [comment]
Amazing. Thanks so much @oliemansm

**Comment by KurtStauffer** [comment]
Thank you!
